name: Broken links

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Defining a new Environment Variable
      run: |                          
        TEMPFILES=$(ls **/*.md)    
        echo "FILES<<EOF" >> $GITHUB_ENV
        echo $TEMPFILES >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --white-list travis-ci,127.0.0.1,smalltalkhub.com/mc,github.com/MY_USERNAME/MY_PROJET_NAME --allow-dupe --allow-redirect --skip-save-results ${{ env.FILES }}
