name: Broken links

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILES: find . -name "*.md"
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: |
        echo ${{ FILES }}
        ls
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --white-list travis-ci,127.0.0.1,smalltalkhub.com/mc --allow-dupe --allow-redirect --skip-save-results $FILES
